Ejercicio para apreder pandas 
En relacion al excel se van a hacer los siguientes pasos: 
1. Carga y exploracion de la informacion
2. Filtrar y segmentar datos 
3. Agruupar y calcular metricas 
4. Limpieza y transformacion de datos
5. Exportacion de resultados a excel

## CARGA Y EXPLORACION DE LA INFORMACION

In [5]:
import pandas as pd 

df = pd.read_excel('trucking_dataset.xlsx', sheet_name='Envíos')

df.head(10) # Este Comando te muestra por defecto 5 Lineas de el Excel

,ID_Envio,Fecha,Cliente,Origen,Destino,Distancia_km,Peso_kg,Tarifa_USD,Estado,Conductor,Camion_ID
0,ENV-0001,2024-11-23,FreightMax,Bogotá,Manizales,328,1319,272.29,Entregado,Carlos Ruiz,CAM-005
1,ENV-0002,2024-08-04,ExpressLoad,Bogotá,Manizales,165,1476,72.51,Entregado,Ana Martínez,CAM-005
2,ENV-0003,2024-08-02,LogiCargo SA,Medellín,Pereira,551,15219,620.18,En tránsito,Pedro López,CAM-003
3,ENV-0004,2024-03-20,TransSur,Cali,Manizales,540,11529,444.02,Entregado,Pedro López,CAM-001
4,ENV-0005,2024-08-23,ExpressLoad,Cali,Manizales,1198,4590,775.52,Entregado,Pedro López,CAM-005
5,ENV-0006,2024-04-08,LogiCargo SA,Medellín,Cartagena,242,2001,231.17,En tránsito,Laura Torres,CAM-003
6,ENV-0007,2024-08-20,TransSur,Bogotá,Manizales,1401,12454,862.06,Entregado,Ana Martínez,CAM-005
7,ENV-0008,2024-05-05,ExpressLoad,Medellín,Cúcuta,434,15647,534.13,Cancelado,Carlos Ruiz,CAM-002
8,ENV-0009,2024-01-17,ExpressLoad,Cali,Santa Marta,746,13645,612.15,Entregado,Laura Torres,CAM-004
9,ENV-0010,2024-11-25,ExpressLoad,Bucaramanga,Cúcuta,1039,5181,574.15,Entregado,Miguel Ríos,CAM-004

In [6]:
df.info()  # Este Comando muestra toda la informacion asi como el indice, columnas, conteo de datos no-null y tipo de dato

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID_Envio      100 non-null    str
 1   Fecha         100 non-null    datetime64[us]
 2   Cliente       100 non-null    str
 3   Origen        100 non-null    str
 4   Destino       100 non-null    str
 5   Distancia_km  100 non-null    int64
 6   Peso_kg       100 non-null    int64
 7   Tarifa_USD    100 non-null    float64
 8   Estado        100 non-null    str
 9   Conductor     100 non-null    str
 10  Camion_ID     100 non-null    str
dtypes: datetime64[us](1), float64(1), int64(2), str(7)
memory usage: 8.7 KB

In [7]:
df.describe() # te da una descripcion simple de las tablas que unicamente tienen datos numericos
#  y te devuelve cosas como un conteo, el promedio y el distinto porcentaje de los valores en el archivo

                     Fecha  Distancia_km       Peso_kg  Tarifa_USD
count                  100    100.000000    100.000000   100.00000
mean   2024-06-29 12:28:48    795.270000  10646.740000   621.31800
min    2024-01-01 00:00:00    100.000000    555.000000    72.51000
25%    2024-03-23 18:00:00    431.500000   5224.500000   470.28250
50%    2024-07-04 00:00:00    747.500000  11099.500000   614.11000
75%    2024-10-01 18:00:00   1147.750000  15229.750000   772.14500
max    2024-12-28 00:00:00   1483.000000  19998.000000  1110.02000
std                    NaN    397.649682   5821.249596   216.21087

In [8]:
df.shape # te devuelve una tupla con el numero de filas y el numero de columnas

(100, 11)

In [9]:
df["Cliente"].value_counts() # Te devuelve el conteo de cada uno de los valores en la Columna que se elija

Cliente
ExpressLoad     25
TransSur        25
LogiCargo SA    21
FreightMax      18
CargoNorte      11
Name: count, dtype: int64

## Filtrar y Segmentar datos

Se establece un filtro para mostrar resultados de una columna especifica junto con los resultados esperados del filtro 
En este codigo se busca cuales son los datos de la columna "Estado" que tienen el valor de "Entregado"
Ademas de que se puede unir con el ".describe()" para ver una version mas resumida e incluso con mas contexto de todo lo que 
incluyen estos **Estados con resultados de Entregado**

In [10]:
# Solo envíos entregados
entregados = df[df["Estado"] == "Entregado"]
print(entregados.describe())

                     Fecha  Distancia_km       Peso_kg   Tarifa_USD
count                   55     55.000000     55.000000    55.000000
mean   2024-07-06 09:36:00    829.854545  10400.527273   627.488364
min    2024-01-01 00:00:00    100.000000   1135.000000    72.510000
25%    2024-03-22 12:00:00    466.000000   4885.500000   447.915000
50%    2024-07-15 00:00:00    746.000000  10682.000000   612.230000
75%    2024-10-09 00:00:00   1220.500000  14880.000000   814.140000
max    2024-12-28 00:00:00   1458.000000  19639.000000  1078.310000
std                    NaN    414.885947   5661.928146   240.965736

Tambien con Tablas que contengan datos **INT** se pueden filtrar con condicionales, ademas de mostrar que se pueden combinar varias de estas funciones por ejemplo, para solo conseguir el numero de tarifas que son mayor a 500

In [11]:
# Envíos con tarifa mayor a $500
caros = df[df["Tarifa_USD"] > 500].value_counts().count()
print(caros)

71

Lo mismo para Tablas con que tengan valores de **str** que de igual manera, recordando que el **.describe()** ignora las columnas de su resultado con texto, solo mantiene las de numero por lo que se tendran que manejar aparte

In [12]:
# Envíos de un cliente específico
logicargo = df[df["Cliente"] == "LogiCargo SA"].describe()
print(logicargo)

                            Fecha  Distancia_km       Peso_kg  Tarifa_USD
count                          21     21.000000     21.000000   21.000000
mean   2024-07-05 18:17:08.571428    767.476190  11224.761905  618.583333
min           2024-01-02 00:00:00    155.000000    681.000000  131.100000
25%           2024-04-08 00:00:00    403.000000   5742.000000  448.500000
50%           2024-08-10 00:00:00    624.000000  12736.000000  620.180000
75%           2024-09-27 00:00:00   1238.000000  15262.000000  814.310000
max           2024-12-24 00:00:00   1458.000000  18650.000000  955.820000
std                           NaN    434.221559   5644.909139  236.722834

La combinacion de condicionales tambien es necesaria para hacer un mayor filtro de los datos que estamos buscando

In [13]:
# Combinar condiciones
retrasados_pesados = df[(df["Estado"] == "Retrasado") & (df["Peso_kg"] > 10000)]
print(f'La cantidad de camiones retrasados de una tonelada son: {retrasados_pesados.value_counts().count()}')
print(retrasados_pesados.describe())

La cantidad de camiones retrasados de una tonelada son: 5
                     Fecha  Distancia_km       Peso_kg  Tarifa_USD
count                    5      5.000000      5.000000    5.000000
mean   2024-06-30 19:12:00    461.200000  17284.600000  585.560000
min    2024-01-30 00:00:00    202.000000  13556.000000  471.550000
25%    2024-04-01 00:00:00    240.000000  13991.000000  509.520000
50%    2024-04-05 00:00:00    495.000000  19236.000000  529.100000
75%    2024-12-03 00:00:00    589.000000  19642.000000  676.360000
max    2024-12-23 00:00:00    780.000000  19998.000000  741.270000
std                    NaN    242.498866   3220.174498  116.681551

## Agrupar y calcular metricas

Para estas metricas es necesario tener un buen entendimiento de los datos que se van a juntar

In [14]:
# Ingresos totales por cliente
ingresos_por_cliente = df.groupby("Cliente")["Tarifa_USD"].sum().sort_values(ascending=False)
print(ingresos_por_cliente)

Cliente
TransSur        17275.08
ExpressLoad     14883.85
LogiCargo SA    12990.25
FreightMax      10942.00
CargoNorte       6040.62
Name: Tarifa_USD, dtype: float64

In [15]:

# Envíos y tarifa promedio por estado
resumen_estado = df.groupby("Estado").agg(
    total_envios=("ID_Envio", "count"),
    tarifa_promedio=("Tarifa_USD", "mean"),
    ingreso_total=("Tarifa_USD", "sum")
)
print(resumen_estado)

             total_envios  tarifa_promedio  ingreso_total
Estado
Cancelado              10       682.095000        6820.95
En tránsito            23       609.470000       14017.81
Entregado              55       627.488364       34511.86
Retrasado              12       565.098333        6781.18

In [ ]:
# Distancia promedio por ruta
rutas = df.groupby(["Origen", "Destino"])["Distancia_km"].mean()
print(rutas)

<pandas.api.typing.DataFrameGroupBy object at 0x0000024813F1CD90>